// import Auth from '@/components/auth';
import React from 'react';

export default function Page() {
    // const user = false;

    // if (!user) {
    //     return (
    //         <div className='container h-screen max-w-7xl mx-auto'>
    //             <Auth />
    //         </div>
    //     );
    // }

    return (
        <div>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aut veritatis tempore officia sint maxime aliquam odit facere ex? Veniam odio harum ex quod praesentium eaque nisi nulla illo aspernatur excepturi fugit, autem, quasi eveniet? Maxime voluptates inventore optio. Quos obcaecati nisi pariatur cum aliquid unde esse, quisquam dignissimos odit dicta magnam, dolorem voluptas repudiandae dolorum temporibus nesciunt debitis et consequuntur quam quaerat. Cumque, eaque accusantium. Voluptatibus praesentium accusantium repudiandae magni delectus nostrum eos odit? Totam fugit obcaecati doloremque ducimus voluptatem animi cupiditate sunt iste debitis, tempore illum saepe deserunt, eos suscipit ratione aliquam earum consectetur optio culpa sint. Voluptate, odio.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda amet voluptas, magni, sunt porro quaerat quos consequuntur quo eos iste reiciendis quia autem dolorum pariatur, natus esse. Quae est, necessitatibus facilis fuga quibusdam fugiat accusamus itaque at officiis fugit, architecto porro provident quia recusandae? Hic, consequuntur illo quaerat sunt delectus id eos ex deserunt quas minus veniam molestias corporis, atque, a voluptatibus saepe fugiat unde quidem aspernatur quisquam sit vero nobis distinctio esse? Libero delectus explicabo expedita voluptatum rerum fuga in amet repudiandae qui nisi deleniti culpa adipisci facere voluptatem, perspiciatis id mollitia officiis quidem ipsa eveniet omnis? Nulla, perspiciatis.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda amet voluptas, magni, sunt porro quaerat quos consequuntur quo eos iste reiciendis quia autem dolorum pariatur, natus esse. Quae est, necessitatibus facilis fuga quibusdam fugiat accusamus itaque at officiis fugit, architecto porro provident quia recusandae? Hic, consequuntur illo quaerat sunt delectus id eos ex deserunt quas minus veniam molestias corporis, atque, a voluptatibus saepe fugiat unde quidem aspernatur quisquam sit vero nobis distinctio esse? Libero delectus explicabo expedita voluptatum rerum fuga in amet repudiandae qui nisi deleniti culpa adipisci facere voluptatem, perspiciatis id mollitia officiis quidem ipsa eveniet omnis? Nulla, perspiciatis.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda amet voluptas, magni, sunt porro quaerat quos consequuntur quo eos iste reiciendis quia autem dolorum pariatur, natus esse. Quae est, necessitatibus facilis fuga quibusdam fugiat accusamus itaque at officiis fugit, architecto porro provident quia recusandae? Hic, consequuntur illo quaerat sunt delectus id eos ex deserunt quas minus veniam molestias corporis, atque, a voluptatibus saepe fugiat unde quidem aspernatur quisquam sit vero nobis distinctio esse? Libero delectus explicabo expedita voluptatum rerum fuga in amet repudiandae qui nisi deleniti culpa adipisci facere voluptatem, perspiciatis id mollitia officiis quidem ipsa eveniet omnis? Nulla, perspiciatis.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda amet voluptas, magni, sunt porro quaerat quos consequuntur quo eos iste reiciendis quia autem dolorum pariatur, natus esse. Quae est, necessitatibus facilis fuga quibusdam fugiat accusamus itaque at officiis fugit, architecto porro provident quia recusandae? Hic, consequuntur illo quaerat sunt delectus id eos ex deserunt quas minus veniam molestias corporis, atque, a voluptatibus saepe fugiat unde quidem aspernatur quisquam sit vero nobis distinctio esse? Libero delectus explicabo expedita voluptatum rerum fuga in amet repudiandae qui nisi deleniti culpa adipisci facere voluptatem, perspiciatis id mollitia officiis quidem ipsa eveniet omnis? Nulla, perspiciatis.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda amet voluptas, magni, sunt porro quaerat quos consequuntur quo eos iste reiciendis quia autem dolorum pariatur, natus esse. Quae est, necessitatibus facilis fuga quibusdam fugiat accusamus itaque at officiis fugit, architecto porro provident quia recusandae? Hic, consequuntur illo quaerat sunt delectus id eos ex deserunt quas minus veniam molestias corporis, atque, a voluptatibus saepe fugiat unde quidem aspernatur quisquam sit vero nobis distinctio esse? Libero delectus explicabo expedita voluptatum rerum fuga in amet repudiandae qui nisi deleniti culpa adipisci facere voluptatem, perspiciatis id mollitia officiis quidem ipsa eveniet omnis? Nulla, perspiciatis.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda amet voluptas, magni, sunt porro quaerat quos consequuntur quo eos iste reiciendis quia autem dolorum pariatur, natus esse. Quae est, necessitatibus facilis fuga quibusdam fugiat accusamus itaque at officiis fugit, architecto porro provident quia recusandae? Hic, consequuntur illo quaerat sunt delectus id eos ex deserunt quas minus veniam molestias corporis, atque, a voluptatibus saepe fugiat unde quidem aspernatur quisquam sit vero nobis distinctio esse? Libero delectus explicabo expedita voluptatum rerum fuga in amet repudiandae qui nisi deleniti culpa adipisci facere voluptatem, perspiciatis id mollitia officiis quidem ipsa eveniet omnis? Nulla, perspiciatis.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda amet voluptas, magni, sunt porro quaerat quos consequuntur quo eos iste reiciendis quia autem dolorum pariatur, natus esse. Quae est, necessitatibus facilis fuga quibusdam fugiat accusamus itaque at officiis fugit, architecto porro provident quia recusandae? Hic, consequuntur illo quaerat sunt delectus id eos ex deserunt quas minus veniam molestias corporis, atque, a voluptatibus saepe fugiat unde quidem aspernatur quisquam sit vero nobis distinctio esse? Libero delectus explicabo expedita voluptatum rerum fuga in amet repudiandae qui nisi deleniti culpa adipisci facere voluptatem, perspiciatis id mollitia officiis quidem ipsa eveniet omnis? Nulla, perspiciatis.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda amet voluptas, magni, sunt porro quaerat quos consequuntur quo eos iste reiciendis quia autem dolorum pariatur, natus esse. Quae est, necessitatibus facilis fuga quibusdam fugiat accusamus itaque at officiis fugit, architecto porro provident quia recusandae? Hic, consequuntur illo quaerat sunt delectus id eos ex deserunt quas minus veniam molestias corporis, atque, a voluptatibus saepe fugiat unde quidem aspernatur quisquam sit vero nobis distinctio esse? Libero delectus explicabo expedita voluptatum rerum fuga in amet repudiandae qui nisi deleniti culpa adipisci facere voluptatem, perspiciatis id mollitia officiis quidem ipsa eveniet omnis? Nulla, perspiciatis.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda amet voluptas, magni, sunt porro quaerat quos consequuntur quo eos iste reiciendis quia autem dolorum pariatur, natus esse. Quae est, necessitatibus facilis fuga quibusdam fugiat accusamus itaque at officiis fugit, architecto porro provident quia recusandae? Hic, consequuntur illo quaerat sunt delectus id eos ex deserunt quas minus veniam molestias corporis, atque, a voluptatibus saepe fugiat unde quidem aspernatur quisquam sit vero nobis distinctio esse? Libero delectus explicabo expedita voluptatum rerum fuga in amet repudiandae qui nisi deleniti culpa adipisci facere voluptatem, perspiciatis id mollitia officiis quidem ipsa eveniet omnis? Nulla, perspiciatis.
        </div>
    );
}
